schema_version = "1.0.0"

id = "group_maker"
version = "1.1.0"
name = "Group Maker (Classical Grouping)"
tagline = "Creates a null (Empty) as a group parent for selected objects with Keep Transform"
maintainer = "Viktor Kom <viktorcor@gmail.com>"
type = "add-on"

tags = ["Object", "Scene", "3D View"]

blender_version_min = "4.0.0"

license = [
  "SPDX:GPL-2.0-or-later",
]

website = "https://github.com/ViktorCor"


